### ISSUE TITLE
Encoding Info is not (completely) visible

### ISSUE THREAD

**Issue by clemens68** [ystsoi/eclipse-fileencodinginfo#4]
Environment:
Win7
Eclipse Mars 4.5.1

The encoding info is "vertically cut", i.e. not really visible/readable. See attached screenshot
![fe1](https://cloud.githubusercontent.com/assets/175240/12191829/6383af0c-b5d9-11e5-92ff-ccd17abd5766.png)

**Comment by ystsoi** [comment]
Thank you for reporting the issue. I can reproduce the issue, and will check the cause later.

**Comment by ystsoi** [comment]
It seems that this issue affects some other Eclipse plugins too:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=471313

I have released 1.3.0, which works around this issue. Please try.
