### ISSUE TITLE
Can support lib inner file encoding dynamic change?

### ISSUE THREAD

**Issue by vongosling** [ystsoi/eclipse-fileencodinginfo#5]

**Comment by ystsoi** [comment]
Do you mean changing encoding for files in JAR and etc?
I found that this is possible, and I have committed the changes.
I will release this feature later.

**Comment by vongosling** [comment]
yeah,like intellij idea,we want to  change the file encoding,wherever the file locates.and we do not want to change project or workset whole encoding

**Comment by ystsoi** [comment]
I have released 1.3.0, which support this feature. Please try.

**Comment by vongosling** [comment]
not work around,my version is eclipse mars.in my here,it display UTF-8(undetected)

**Comment by ystsoi** [comment]
What file do you open? The plugin only supports some types of files. (More precisely, it only supports some types of editors.) I have tested the plugin with properties files inside JARs.

**Comment by vongosling** [comment]
class files in jars,xml files not in jar,all display the same result "UTF-8(undetected)".can you plan to support here?

**Comment by ystsoi** [comment]
Yes, I will see whether it is feasible.

**Comment by ystsoi** [comment]
I have released 1.4.0, which supports XML Editor, HTML Editor, and etc. But I cannot find a solution for class files.

**Comment by vongosling** [comment]
thank you . i also have no idea nowadays if i intalled maven eclipse plugin. how to change the source code file encoding not the same with default settings ~

**Comment by ystsoi** [comment]
Project-level or file-level file encoding can be set via File > Properties > Resource.
File-level file encoding can usually be set via Edit > Set Encoding... too.

**Comment by vongosling** [comment]
yeah.i mean.i don't know the eclipse plugin(RCP) solution.so i can not give your advice how to do my requirement as this issue said.
